spring.application.name=HotelServer

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db
spring.datasource.username=root
spring.datasource.password=Sandesh@1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Security Configurations
#spring.security.user.name=admin
#spring.security.user.password=admin123

# Enable SQL logging
spring.jpa.show-sql=true

# Format SQL queries for better readability
spring.jpa.properties.hibernate.format_sql=true

#if you want to avoid this specific exception and allow Jackson to serialize even empty beans, you can configure Jackson to disable the FAIL_ON_EMPTY_BEANS feature. This can be done globally in your application.properties or programmatically.
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.deserialization.fail-on-unknown-properties =false

